name: Trigger reset - WordPress Cron Job 

on:
  # schedule:
  #   # This cron expression will run at 0:00 AM.
  #   - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Make HTTP request to trigger cron
        run: curl --request GET 'https://gogos-corps.gr/wp/trigger-cron.php?key=${{ secrets.CRON_KEY }}&reset=1'
